Tuple1=()
print("Initial empty tuple:")
print(Tuple1)
Tuple1=('Geeks','for')
print("\nTuple with use of String:")
print(Tuple1)
list1=[1,2,3,4,5,6]
print("\nTuple using list:")
print(tuple(list1))
Tuple1=tuple('Geeks')
print("\nTuple with use of a function:")
print(Tuple1)
Tuple1=(0,1,2,3)
Tuple2=('python','Geek')
Tuple3=(Tuple1,Tuple2)
print("\nTuple with nested Tuples:")
print(Tuple3)